export const REACT_APP_CLIENT_ID = process.env.REACT_APP_CLIENT_ID
export const REACT_APP_CLIENT_SECRET = process.env.REACT_APP_CLIENT_SECRET
export const REACT_APP_REFRESH_TOKEN = process.env.REACT_APP_REFRESH_TOKEN